[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

solc_remaps = [
    "ds-test/=lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
  ]

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
